### ISSUE TITLE
可不可以帮我也整一个

### ISSUE THREAD

**Issue by qaqland** [zj360202/robotgo_mouse#1]
```
package main

import (
	"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.TypeStr("cd 桌面")
}
```
我在写一个终端的输入法（toy），整个项目看下来只需要用到这一句...
有没有其他功能类似的项目推荐或者能不能按照这个函数精简一下qaq
磕头了(_　_)。出来之后一定一键三连

**Comment by zj360202** [comment]
这个直接保留对应的包中对的c与golang中的接口，然后试下就好了，我这边有几个项目，真心没有精力啊！
1. 你创建一个vgo项目，
2. 将robotgo项目复制进去
3. 运行测试一下是否可以通
4. 然后不断的删除不用的模块就可以了

**Comment by qaqland** [comment]
好的谢谢您的回复！
